### ISSUE TITLE
Bugs in profile page and log-in page from mobile client

### ISSUE THREAD

**Issue by qiblaqi** [wuhuwuhuhu/InterNatter#2]
Showing by following screen shots, the profile page and log in page cant be shown properly in mobile client

// profile page
![IMG_0219](https://user-images.githubusercontent.com/16836184/113180476-c6634200-921e-11eb-9706-05c1f4d23b55.PNG)

// log in page
![IMG_0220](https://user-images.githubusercontent.com/16836184/113180778-21953480-921f-11eb-9945-2b473e5e77ec.PNG)

**Comment by wuhuwuhuhu** [comment]
This issue has been solved by redesign
