### ISSUE TITLE
Minor bugs involved with new multi-language UI commit April 12th

### ISSUE THREAD

**Issue by qiblaqi** [wuhuwuhuhu/InterNatter#4]
1. Missing the translation for the new chatroom page
![Screen Shot 2021-04-12 at 7 12 41 PM](https://user-images.githubusercontent.com/16836184/114474104-85c2db80-9bc3-11eb-815b-71be27cd8171.png)

2. Missing the translation for the pending friend list status label, accept decline button, and friend information(expecting the language preferrence part to be translated; eg. Chinese(simplified) -> needs to be translated to “简体中文” )
![Screen Shot 2021-04-12 at 7 14 00 PM](https://user-images.githubusercontent.com/16836184/114474374-17324d80-9bc4-11eb-991e-b11559a41edc.png)

**Comment by wuhuwuhuhu** [comment]
Thanks for your issues report.
this issue has been resolved. Please try again. And If it passes the tests, please close this issue.
@qiblaqi

**Comment by qiblaqi** [comment]
thanks for the notice.
